### ISSUE TITLE
Create docker-compose.yml for dependent containers

### ISSUE THREAD

**Issue by gen1us2k** [maddevsio/comedian#6]

**Comment by anatoliyfedorenko** [comment]
neet to add health check. https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y

**Comment by anatoliyfedorenko** [comment]
added healthcheck for db:
```
healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 1s
      retries: 120
```
and condition for the app: 
```
depends_on:
      - "db"
```
in https://github.com/maddevsio/comedian/blob/master/docker-compose.yml
